[book]
title = "Data Visualization Techniques Demo"
authors = ["jim-wyatt"]
description = "Master data visualization across Python's top libraries. Comprehensive examples using Matplotlib, Seaborn, Plotly, and more."
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
mathjax-support = true

[output.html.fold]
enable = false

[output.html.playground]
editable = false
